datawarehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST_PROD') }}"
      user: "{{ env_var('DB_USER_PROD') }}"
      pass: 5KJMTAxqe0C0msSWAMxVqaCKlhxW99iR5KJMTAxqe0C0msSWAMxVqaCKlhxW99iR5KJMTAxqe0C0msSWAMxVqaCKlhxW99iR5KJMTAxqe0C0msSWAMxVqaCKlhxW99iR5KJMTAxqe0C0msSWAMxVqaCKlhxW99iRsdadasaseeeer
      port: "{{ env_var('DB_PORT_PROD') | int }}"
      dbname: "{{ env_var('DB_NAME_PROD') }}"
      schema: "{{ env_var('DB_SCHEMA_PROD') }}"
      threads: "{{ env_var('DB_THREADS_PROD') | int }}"
      keepalives_idle: 0